# Generated by Django 2.2 on 2020-06-26 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manast_site.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, unique=True, verbose_name='holiday_name')),
                ('date', models.DateField(blank=True, unique=True, verbose_name='holiday_date')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True, verbose_name='weekday')),
                ('from_hour', models.TimeField(blank=True)),
                ('rest_hour', models.TimeField(blank=True)),
                ('comeback_hour', models.TimeField(blank=True)),
                ('to_hour', models.TimeField(blank=True)),
            ],
            options={
                'ordering': ('op_weekday', 'from_hour'),
                'unique_together': {('op_weekday', 'from_hour', 'rest_hour', 'comeback_hour', 'to_hour')},
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name_shop')),
                ('photo', models.ImageField(blank=True, default='shops/shop.png', storage=manast_site.models.MediaFileSystemStorage(), upload_to='shops', verbose_name='photo')),
                ('direction', models.CharField(blank=True, max_length=50, verbose_name='direction_shop')),
                ('zip_code', models.CharField(blank=True, max_length=5, verbose_name='zip_code_shop')),
                ('phone', models.CharField(blank=True, max_length=9, verbose_name='phone_shop')),
                ('holidays', models.ManyToManyField(blank=True, related_name='holidays_shop', to='manast_site.Holiday', verbose_name='holidays_shop')),
                ('opening_times', models.ManyToManyField(blank=True, related_name='opening_hours_shop', to='manast_site.OpeningHours', verbose_name='opening_hours_shop')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/user.png', storage=manast_site.models.MediaFileSystemStorage(), upload_to='avatars', verbose_name='avatar')),
                ('shops', models.ManyToManyField(blank=True, to='manast_site.Shop', verbose_name='shops_user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
