# Generated by Django 2.2 on 2020-05-30 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manast_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name_category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manast_site.Profile')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name_item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manast_database.Category', verbose_name='type_item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manast_site.Shop')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sale', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='quantity_sale')),
                ('price_sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price_sale')),
                ('cost_sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='cost_sale')),
                ('date_sale', models.DateField(default=datetime.date.today, verbose_name='date_sale')),
                ('item_sale', models.ManyToManyField(to='manast_database.Item')),
                ('shop_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manast_site.Shop')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_exp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='quantity_expense')),
                ('cost_exp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='cost_expense')),
                ('date_exp', models.DateField(default=datetime.date.today, verbose_name='date_exp')),
                ('periodicity_exp', models.IntegerField(default=1, verbose_name=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly '), (4, 'Annual')])),
                ('repeat_exp', models.BooleanField(default=False, verbose_name='repeat_expense')),
                ('item_exp', models.ManyToManyField(to='manast_database.Item')),
                ('shop_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manast_site.Shop')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
